default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: whats_the_gruff

test:
  <<: *default
  database: whats_the_gruff_test

production:
  <<: *default
  database: whats_the_gruff
